Added documentation and submodule repo
10x-Engineers/riscv-ci-partners pull request #6
Opened 2022-10-06 10:01 UTC by alitariq4589

- I have changed the documentation of github_webhook_integration to github_push_webhook_integration considering the fact that jenkins' built-in plugin can only be used to trigger job for push in the specified branch and not when pull request is created.
- I have added the documentation about using `Github Pull Request Builder` plugin and how it can be used to trigger the pipeline build when a pull request for merge is generated.
- Adding path of a package in .bashrc does not work in jenkins, so I have added documentation to add the package's path to $PATH variable in jenkins node configuration.
- Also I have added new submodule repository.

2022-10-06 13:45 UTC, mmoizhussain requested changes

2022-10-06 15:18 UTC, alitariq4589 commented on jenkins_docs/Github_push_webhook.md
> +![Screenshot from 2022-09-26 16-39-29](https://user-images.githubusercontent.com/99069972/192314484-a761bb98-5fbe-4303-9627-d42ff1f096e1.png)
Okay

2022-10-06 16:01 UTC, alitariq4589 commented on jenkins_docs/Building_Jenkins_github_repo.md
> +<p align="center">
I have reverted them back. I did not add a brief message with them when making changes so it was pretty hectic changing them again.

2022-10-07 07:46 UTC, alitariq4589 commented on jenkins_docs/Creating_Jenkins_Node_on_LXC.md
>  ![unnamed (14)](https://user-images.githubusercontent.com/99069972/190384770-a8f2fcff-081a-470a-913a-2982f943f16d.png)
Those are added from local directory. Btw I have tried to give local path to images on github markdown but the path does not resolve.

2022-10-07 13:36 UTC, alitariq4589 commented on jenkins_docs/Creating_Jenkins_Node_on_LXC.md
>  ![unnamed (14)](https://user-images.githubusercontent.com/99069972/190384770-a8f2fcff-081a-470a-913a-2982f943f16d.png)
I have added relative paths of all the images in all documentations and the images are present in `doc_images`.

2022-10-17 08:00 UTC, mmoizhussain approved these changes

2022-10-17 08:01 UTC, merged